"""Initial tables

Revision ID: bb915c6eb8a9
Revises: 
Create Date: 2026-02-07 00:36:13.870255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb915c6eb8a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('geo_tasks',
    sa.Column('task_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('cloro_task_id', sa.String(length=100), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('target_user', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_url_used', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('geo_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('cloro_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shopping_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('places', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citation_pills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['geo_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_results')
    op.drop_table('geo_tasks')
    # ### end Alembic commands ###