import asyncio
import logging
import json
from sqlalchemy import insert, select, delete
from src.core.database import database, geo_tasks, geo_results
from dotenv import load_dotenv

# Load env vars
load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("DB_Debug")

async def main():
    logger.info("--- Starting Database Integration Test ---")
    
    # 1. Connect
    logger.info("Connecting to database...")
    await database.connect()
    
    try:
        # 2. Insert a Test Task
        logger.info("Inserting test task...")
        task_data = {
            "client_name": "TestClient_Local",
            "product": "Acme",
            "country": "US",
            "platform": "chatgpt",
            "prompt_text": "What do you know about Acme Corp?",
            "target_user": {"persona": "developer", "age": 30},
            "batch_id": "TEST-BATCH-001", # Added batch_id explicitly
            "status": "PENDING"
        }
        
        # task_id is generated by DB (server_default)
        stmt = insert(geo_tasks).values(**task_data).returning(geo_tasks.c.task_id)
        task_id = await database.fetch_val(stmt)
        logger.info(f"Task inserted with ID: {task_id}")
        
        # 3. Verify Insertion
        query = select(geo_tasks).where(geo_tasks.c.task_id == task_id)
        row = await database.fetch_one(query)
        logger.info(f"Fetched Task Status: {row['status']}")
        assert row['status'] == 'PENDING'
        
        # 4. Simulate Worker Ingestion (Insert Result + Update Task)
        logger.info("Simulating worker ingestion...")
        
        # Real Cloro Response Mock
        mock_response = {
          "success": True,
          "result": {
            "text": "The name \"Acme Corporation\" is used in various contexts...",
            "sources": [
              {
                "position": 1,
                "url": "https://www.rippling.com/blog/ai-recruiting?utm_source=chatgpt.com",
                "label": "Rippling",
                "description": "12 Best AI Recruiting Tools For HR in 2025 | Rippling"
              }
            ],
            "html": "https://storage.cloro.dev/results/c45a5081-808d-4ed3-9c86-e4baf16c8ab8/page-1.html",
            "markdown": "The name \"Acme Corporation\" is used in various contexts...",
            "rawResponse": [
              {
                "type": "message_start",
                "message": {
                  "id": "msg_01JD6Q7H1ZKWM9GD34V5ZW1TYM",
                  "role": "assistant",
                  "model": "gpt-5"
                }
              }
            ],
            "searchQueries": [
              "What is Acme Corporation?",
              "Acme Corp company overview"
            ],
            "model": "gpt-5",
            "shoppingCards": [
              {
                "tags": ["stylish casual leather sneaker"],
                "products": [
                  {
                    "title": "Adidas VL Court 3.0",
                    "url": "https://www.adidas.com/us/vl-court-3.0-shoes/ID8797.html",
                    "price": "$57.00",
                    "merchant": "adidas + others",
                    "rating": 4.7
                  }
                ]
              }
            ],
            "entities": [
              {"type": "product", "name": "adidas Grand Court Lo"}
            ]
          }
        }
        
        # Insert Result
        stmt_result = insert(geo_results).values(
            task_id=task_id,
            cloro_response=mock_response,
            http_status_code=200,
            latency_ms=1250
        )
        await database.execute(stmt_result)
        logger.info("Result inserted into geo_results.")
        
        # Update Task Status
        from sqlalchemy import update
        stmt_update = (
            update(geo_tasks)
            .where(geo_tasks.c.task_id == task_id)
            .values(status="COMPLETED")
        )
        await database.execute(stmt_update)
        logger.info("Task status updated to COMPLETED.")
        
        # 5. Final Verification
        row_final = await database.fetch_one(query)
        logger.info(f"Final Task Status: {row_final['status']}")
        assert row_final['status'] == 'COMPLETED'
        
        # Verify JSONB storage
        query_result = select(geo_results).where(geo_results.c.task_id == task_id)
        row_result = await database.fetch_one(query_result)
        
        # FIX: asyncpg automatically deserializes JSONB to dict, so no need for json.loads()
        stored_json = row_result['cloro_response'] 
        
        # Check if shoppingCards are preserved
        cards = stored_json['result'].get('shoppingCards', [])
        logger.info(f"Stored Shopping Cards count: {len(cards)}")
        assert len(cards) > 0
        
        logger.info("--- Test Passed Successfully! ---")

    except Exception as e:
        logger.error(f"Test Failed: {e}")
        raise
    finally:
        await database.disconnect()

if __name__ == "__main__":
    asyncio.run(main())