"""Canonical technical feature registry.

This module is the only authoring source for feature keys, frontend route
ownership, and the initial Admin/Viewer capability matrix.  Database rows may
customize display metadata, packages, and workspace entitlements, but they
must reference a feature key declared here.

The SaaS TypeScript mirror is generated by
``scripts/generate_feature_registry.py`` and must never be edited by hand.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from fnmatch import fnmatchcase
from typing import Literal

Capability = Literal["view", "execute", "manage"]
CAPABILITIES: tuple[Capability, ...] = ("view", "execute", "manage")


@dataclass(frozen=True)
class FeatureModule:
    key: str
    label_zh: str
    label_en: str
    sort_order: int


@dataclass(frozen=True)
class RoutePolicy:
    """A declarative backend route rule.

    ``path`` uses shell-style ``*`` matching. Dynamic request semantics that
    cannot be derived from method/path alone (notably Agent task type) are
    resolved by the service dependency before evaluating the capability.
    """

    service: Literal["saas", "agent"]
    methods: tuple[str, ...]
    path: str
    capability: Capability
    audit: bool = False
    system_job: bool = False


@dataclass(frozen=True)
class FeatureDefinition:
    key: str
    module_key: str
    label_zh: str
    label_en: str
    description_zh: str
    description_en: str
    sort_order: int
    frontend_routes: tuple[str, ...]
    backend_routes: tuple[RoutePolicy, ...] = ()


MODULES: tuple[FeatureModule, ...] = (
    FeatureModule("analytics", "数据分析与洞察", "Data Analysis & Monitoring", 10),
    FeatureModule("actions", "Actions", "Actions", 20),
)


def _route(
    service: Literal["saas", "agent"],
    methods: tuple[str, ...],
    path: str,
    capability: Capability,
    *,
    audit: bool = False,
    system_job: bool = False,
) -> RoutePolicy:
    return RoutePolicy(service, methods, path, capability, audit, system_job)


FEATURE_REGISTRY: tuple[FeatureDefinition, ...] = (
    FeatureDefinition(
        "analytics.overview",
        "analytics",
        "可见度总览",
        "Overview",
        "汇总查看品牌的核心 GEO 指标与趋势。",
        "View a summary of core GEO metrics and trends.",
        10,
        ("/overview",),
        (
            _route("saas", ("GET",), "/api/insights/overview*", "view"),
        ),
    ),
    FeatureDefinition(
        "analytics.visibility",
        "analytics",
        "可见度",
        "Visibility",
        "查看品牌、产品和渠道的可见度表现。",
        "Explore brand, product, and channel visibility.",
        20,
        (
            "/insights",
            "/insights/visibility*",
            "/insights/citations*",
            "/insights/channel-analysis*",
        ),
        (
            _route("saas", ("GET", "POST"), "/api/insights/visibility*", "view"),
            _route("saas", ("GET", "POST"), "/api/insights/channel*", "view"),
            _route("saas", ("GET", "POST"), "/api/insights/product*", "view"),
            _route("saas", ("GET", "POST"), "/api/insights/analysis*", "view"),
            _route("saas", ("GET",), "/api/insights/availability*", "view"),
            _route("saas", ("GET",), "/api/insights/peer-sov*", "view"),
            _route("saas", ("GET",), "/api/insights/shadow*", "view"),
            _route("saas", ("GET",), "/api/insights/topic-visibility*", "view"),
        ),
    ),
    FeatureDefinition(
        "analytics.citations",
        "analytics",
        "引用",
        "Citations",
        "查看引用来源、域名和页面表现。",
        "Inspect cited sources, domains, and pages.",
        30,
        ("/citation*",),
        (
            _route("saas", ("GET", "POST"), "/api/insights/citation*", "view"),
            _route("saas", ("GET", "POST"), "/api/citation*", "view"),
            _route("saas", ("GET",), "/api/published-urls*", "view"),
            _route("saas", ("GET",), "/api/insights/cited-*", "view"),
            _route("saas", ("GET",), "/api/insights/published-url-tracking*", "view"),
        ),
    ),
    FeatureDefinition(
        "analytics.sentiment",
        "analytics",
        "引用情感",
        "Sentiment",
        "查看品牌和引用内容的情感分布。",
        "Review sentiment across brands and citations.",
        40,
        ("/sentiment*",),
        (
            _route("saas", ("GET", "POST"), "/api/sentiment*", "view"),
            _route("saas", ("GET", "POST"), "/api/insights/sentiment*", "view"),
            _route("saas", ("GET",), "/api/insights/product-sentiment*", "view"),
        ),
    ),
    FeatureDefinition(
        "analytics.prompts",
        "analytics",
        "Prompt 报告",
        "Prompt Reports",
        "查看 Prompt、主题、扇出和单次回答明细。",
        "Review prompts, topics, fan-outs, and individual responses.",
        50,
        (
            "/insights/prompts*",
            "/insights/fanouts*",
            "/prompts*",
        ),
        (
            _route("saas", ("GET",), "/api/prompts*", "view"),
            _route("saas", ("GET", "POST"), "/api/insights/prompt*", "view"),
            _route("saas", ("GET", "POST"), "/api/insights/fanout*", "view"),
            _route("saas", ("POST",), "/api/brainstorming/generate*", "manage", audit=True),
            _route("saas", ("POST", "PUT", "PATCH", "DELETE"), "/api/prompts*", "manage", audit=True),
        ),
    ),
    FeatureDefinition(
        "analytics.reports",
        "analytics",
        "Reports",
        "Reports",
        "生成并查看动态日期范围报告入口。",
        "Materialize and view dynamic date-range report entries.",
        60,
        ("/reports*", "/share/reports*"),
        (
            _route("saas", ("GET",), "/api/static-reports*", "view"),
            # Current dynamic-report-v1 materialization is intentionally a
            # lightweight view operation, including for Viewer.
            _route("saas", ("POST",), "/api/static-reports/today/materialize*", "view", audit=True),
            _route("saas", ("POST",), "/api/static-reports/materialize-date*", "view", audit=True),
            _route("saas", ("PUT", "PATCH", "DELETE"), "/api/static-reports*", "manage", audit=True),
        ),
    ),
    FeatureDefinition(
        "actions.configuration",
        "actions",
        "配置",
        "Configuration",
        "查看或维护 Workspace 品牌、竞品、主题和 Prompt 配置。",
        "View or maintain workspace brands, peers, topics, and prompts.",
        10,
        (
            "/agents/tracking*",
            "/settings*",
            "/prompt-editor*",
            "/brand-hub*",
            "/knowledge*",
        ),
        (
            _route("saas", ("GET",), "/api/settings*", "view"),
            _route("saas", ("GET",), "/api/clients*", "view"),
            _route("saas", ("GET",), "/api/workspaces*", "view"),
            _route("saas", ("GET",), "/api/onboarding*", "view"),
            _route("saas", ("GET",), "/api/intents*", "view"),
            _route("saas", ("GET",), "/api/platforms*", "view"),
            _route("saas", ("GET",), "/api/languages*", "view"),
            _route("saas", ("POST", "PUT", "PATCH", "DELETE"), "/api/settings*", "manage", audit=True),
            _route("saas", ("POST", "PUT", "PATCH", "DELETE"), "/api/clients*", "manage", audit=True),
            _route("saas", ("POST", "PUT", "PATCH", "DELETE"), "/api/onboarding*", "manage", audit=True),
            _route("saas", ("POST", "PUT", "PATCH", "DELETE"), "/api/published-urls*", "manage", audit=True),
        ),
    ),
    FeatureDefinition(
        "actions.analysis",
        "actions",
        "分析内容",
        "Analyze",
        "查看分析任务结果；管理员可创建、运行、编辑和删除任务。",
        "View analysis results; Admins can create, run, edit, and delete tasks.",
        20,
        ("/agents/analysis*", "/report/*"),
        (
            _route("agent", ("GET",), "/api/agent/tasks*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/*/export*", "view", audit=True),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/tasks*", "execute", audit=True),
            _route("agent", ("GET",), "/api/agent/tasks/templates*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/workflow-config*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/framework*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/metrics*", "view"),
        ),
    ),
    FeatureDefinition(
        "actions.content",
        "actions",
        "内容生成",
        "Content Generation",
        "查看已生成文章；管理员可创建和执行内容任务。",
        "View generated articles; Admins can create and execute content tasks.",
        30,
        ("/agents/content*",),
        (
            # Task-list/detail routes are resolved by task_type in the Agent
            # dependency so analysis and content remain independently gated.
            _route("agent", ("GET",), "/api/agent/tasks*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/*/export*", "view", audit=True),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/tasks*", "execute", audit=True),
            _route("agent", ("POST",), "/api/agent/tasks/generate-strategy*", "execute", audit=True),
            _route("agent", ("GET", "POST"), "/api/agent/tasks/content*", "execute", audit=True),
            _route("agent", ("GET",), "/api/agent/tasks/prompts/ranked*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/topics/ranked*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/client-platforms*", "view"),
            _route("agent", ("POST",), "/api/agent/tasks/reddit*", "execute", audit=True),
            _route("agent", ("POST",), "/api/agent/tasks/official-website*", "execute", audit=True),
            _route("agent", ("POST",), "/api/agent/action/review*", "execute", audit=True),
            _route("agent", ("GET",), "/api/agent/tasks/templates*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/workflow-config*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/framework*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/metrics*", "view"),
            _route("agent", ("GET",), "/api/agent/brand-profile*", "view"),
        ),
    ),
    FeatureDefinition(
        "actions.chat",
        "actions",
        "对话 Anthony",
        "Chat with Anthony",
        "通过 Anthony 对话执行跨模块分析与协作。",
        "Use Anthony for conversational analysis and collaboration.",
        40,
        ("/agents/chat*",),
        (
            _route("agent", ("GET", "POST", "PUT", "PATCH", "DELETE"), "/api/agent/chat*", "execute", audit=True),
            _route("agent", ("GET", "POST", "PUT", "PATCH", "DELETE"), "/api/agent/sessions*", "execute", audit=True),
            _route("agent", ("GET",), "/api/agent/toolbar/status*", "execute"),
        ),
    ),
    FeatureDefinition(
        "actions.training",
        "actions",
        "训练 Anthony",
        "Train Anthony",
        "配置 Anthony 的模板、框架和训练资源。",
        "Configure Anthony templates, frameworks, and training resources.",
        50,
        ("/agents/training*",),
        (
            _route("agent", ("GET",), "/api/agent/tasks/templates*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/workflow-config*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/framework*", "view"),
            _route("agent", ("GET",), "/api/agent/tasks/metrics*", "view"),
            _route("agent", ("GET",), "/api/agent/memories*", "view"),
            _route("agent", ("GET",), "/api/agent/brand-profile*", "view"),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/tasks/templates*", "manage", audit=True),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/tasks/workflow-config*", "manage", audit=True),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/tasks/framework*", "manage", audit=True),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/tasks/metrics*", "manage", audit=True),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/memories*", "manage", audit=True),
            _route("agent", ("POST", "PUT", "PATCH", "DELETE"), "/api/agent/brand-profile*", "manage", audit=True),
        ),
    ),
)


# Capability inheritance is intentionally explicit:
# manage -> execute -> view. Viewer gets only view on the agreed surfaces.
ROLE_CAPABILITIES: dict[str, dict[str, tuple[Capability, ...]]] = {
    "admin": {
        feature.key: CAPABILITIES
        for feature in FEATURE_REGISTRY
    },
    "viewer": {
        "analytics.overview": ("view",),
        "analytics.visibility": ("view",),
        "analytics.citations": ("view",),
        "analytics.sentiment": ("view",),
        "analytics.prompts": ("view",),
        "analytics.reports": ("view",),
        "actions.configuration": ("view",),
        "actions.analysis": ("view",),
        "actions.content": ("view",),
    },
    # Internal roles deliberately bypass Workspace package entitlements. The
    # role matrix still declares their capabilities so backend and frontend
    # use one authorization contract.
    "account_manager": {
        feature.key: CAPABILITIES
        for feature in FEATURE_REGISTRY
    },
    "super_admin": {
        feature.key: CAPABILITIES
        for feature in FEATURE_REGISTRY
    },
}


def get_feature(feature_key: str) -> FeatureDefinition:
    for feature in FEATURE_REGISTRY:
        if feature.key == feature_key:
            return feature
    raise KeyError(f"Unknown feature key: {feature_key}")


def capability_allowed(role: str, feature_key: str, capability: Capability) -> bool:
    return capability in ROLE_CAPABILITIES.get(role, {}).get(feature_key, ())


def resolve_frontend_feature(pathname: str) -> FeatureDefinition | None:
    normalized = pathname if pathname.startswith("/") else f"/{pathname}"
    for feature in FEATURE_REGISTRY:
        if any(fnmatchcase(normalized, pattern) for pattern in feature.frontend_routes):
            return feature
    return None


def resolve_backend_policies(
    service: Literal["saas", "agent"],
    method: str,
    path: str,
) -> tuple[tuple[FeatureDefinition, RoutePolicy], ...]:
    """Resolve the most-specific registered policies for an API request."""
    matches: list[tuple[int, FeatureDefinition, RoutePolicy]] = []
    normalized_method = method.upper()
    for feature in FEATURE_REGISTRY:
        for policy in feature.backend_routes:
            if policy.service != service or normalized_method not in policy.methods:
                continue
            if not fnmatchcase(path, policy.path):
                continue
            specificity = len(policy.path.replace("*", ""))
            matches.append((specificity, feature, policy))
    if not matches:
        return ()
    max_specificity = max(item[0] for item in matches)
    return tuple(
        (feature, policy)
        for specificity, feature, policy in matches
        if specificity == max_specificity
    )


def registry_payload() -> dict[str, object]:
    """Return the deterministic JSON-compatible frontend contract."""
    return {
        "version": 1,
        "capabilities": list(CAPABILITIES),
        "modules": [asdict(module) for module in MODULES],
        "features": [
            {
                **asdict(feature),
                "frontend_routes": list(feature.frontend_routes),
                "backend_routes": [
                    {
                        **asdict(route),
                        "methods": list(route.methods),
                    }
                    for route in feature.backend_routes
                ],
            }
            for feature in FEATURE_REGISTRY
        ],
        "role_capabilities": {
            role: {
                feature_key: list(capabilities)
                for feature_key, capabilities in feature_capabilities.items()
            }
            for role, feature_capabilities in ROLE_CAPABILITIES.items()
        },
    }
