#!/usr/bin/env python3
"""Generate the frontend mirror of the canonical Python feature registry."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
COMMON_SRC = REPO_ROOT / "geo_common" / "src"
OUTPUT = (
    REPO_ROOT
    / "geo_saas"
    / "web"
    / "src"
    / "generated"
    / "featureRegistry.generated.ts"
)

sys.path.insert(0, str(COMMON_SRC))

from geo_common.permissions import registry_payload  # noqa: E402


def render() -> str:
    payload = registry_payload()
    serialized = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    digest = hashlib.sha256(serialized.encode("utf-8")).hexdigest()
    pretty = json.dumps(payload, ensure_ascii=False, indent=2)
    return (
        "/* eslint-disable */\n"
        "// AUTO-GENERATED by scripts/generate_feature_registry.py.\n"
        "// Do not edit this file directly.\n"
        f"export const FEATURE_REGISTRY_SHA256 = {json.dumps(digest)} as const;\n"
        f"export const FEATURE_REGISTRY = {pretty} as const;\n"
        "export type FeatureKey = typeof FEATURE_REGISTRY.features[number]['key'];\n"
        "export type FeatureCapability = typeof FEATURE_REGISTRY.capabilities[number];\n"
        "export type WorkspaceRole = keyof typeof FEATURE_REGISTRY.role_capabilities;\n"
    )


def main() -> int:
    expected = render()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"Out of date: {OUTPUT.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(OUTPUT.relative_to(REPO_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
